name: 'Release Client Spec'
on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Publish to npm
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - run: |
        yarn install --frozen-lockfile
    - run: |
        TAG=$(echo $GITHUB_REF_NAME | grep -oP '^v\d+\.\d+\.\d+-?\K(\w+)?')
        npm publish --tag ${TAG:-latest}
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}